version: '3'
services:
  payments-gateway:
    image: payments-gateway
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: payments-gateway
    working_dir: /app
    entrypoint:
      - sh
      - -c
      - sleep 10; diesel migration run; /usr/local/cargo/bin/cargo run server
    volumes:
      - ..:/app
    environment:
      - DATABASE_URL=postgresql://payments-gateway:payments-gateway@payments-gateway-pg/payments-gateway
      - "RUST_LOG=payments_gateway=debug"
    expose:
      - 8000
    ports:
      - 8000:8000
    stdin_open: true
    depends_on:
      - payments-gateway-pg

  payments-gateway-pg:
    image: postgres:10
    container_name: payments-gateway-pg
    volumes:
      - stq-payments-gateway-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=payments-gateway
      - POSTGRES_DB=payments-gateway
      - POSTGRES_PASSWORD=payments-gateway
    expose:
      - 5432

volumes:
  stq-payments-gateway-postgres-data:

networks:
  default:
    external:
      name: payments
